version: '3.8'

services:
  node:
    build:
      context: .
      target: release
    command: npm run start:prod
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/home/node/app/src
      - ./logs:/home/node/app/logs
      - /home/node/app/node_modules
    restart: unless-stopped
    networks:
      - app-bridge

  postgres:
    build: ./src/database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-bridge

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app-bridge

networks:
  app-bridge:
    driver: bridge

volumes:
  pgdata:
  pgadmin:
